FROM rocker/r2u

RUN apt update 
RUN apt install -y texinfo git vim qpdf
RUN apt install -y libcurl4-openssl-dev 
# for rcmdcheck via curl
RUN apt install -y zlib1g-dev 
# for qpdf
RUN apt install -y libssl-dev 
# for httr -> UCSC.utils -> GenomeInfoDb -> GRanges -> SE
RUN apt install -y libxml2-dev libpng-dev liblzma-dev libbz2-dev 
# for tximeta, Rhtslib, XML, etc.
# might as well install pandoc and avoid doing it in action?
RUN apt install -y pandoc

RUN Rscript -e "install.packages(c('BiocManager', 'BiocCheck', 'BiocStyle', 'knitr', 'rmarkdown', 'rcmdcheck', 'tinytex', 'qpdf'), update=TRUE, ask=FALSE)"
RUN Rscript -e "library(tinytex); tinytex::install_tinytex(); tinytex::tlmgr_install('courier')"
ENV PATH="$PATH:/root/.TinyTeX/bin/x86_64-linux"
